---
author: "Daniela Palleschi"
institute: Humboldt-Universität zu Berlin
# footer: "Lecture 1.1 - R und RStudio"
lang: en
date: "`r Sys.Date()`"
format:
  html:
    number-sections: true
    number-depth: 3
    toc: true
    code-overflow: wrap
    code-tools: true
    self-contained: true
    fig-width: 6
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    fig-width: 4
    code-overflow: wrap
bibliography: references.bib
csl: apa.csl
execute: 
  eval: true # evaluate chunks
  echo: true # 'print code chunk?'
  message: false # 'print messages (e.g., warnings)?'
  error: true # ignore errors when rendering?
  warning: false
---

# Course overview {.unnumbered}

This course fast tracks through different types of regression most relevant to linguistic research. These materials are by no means exhaustive, and should be supplemented by reading textbook length treatments. The majority of my materials lean heavily on @winter_statistics_2019, which I highly recommend. I also took inspiration from @sonderegger_regression_nodate-1, which came out this year and I haven't fully explored yet. So far, it looks like a very thorough textbook that I would also recommend you check out.

Before you begin the course, I would like to paraphrase something Prof. Shravan Vasishth said in the opening remarks for the annual summer school for Statistcal Methods for Linguistics and Psychology back in 2020 which has stuck with me: *get comfortable with partial knowledge*. We are not trained statisticians, and likely never will be (Vasishth himself is a certified statistician, in addition to professor of psycholinguistics). So get comfortable with partial understanding of the math behind these models, and focus on their application and interpretation.

## Moodle

- lecture materials

# Course credit

This course is part of [Modul 9 (Forschungsmodul)](https://gremien.hu-berlin.de/de/amb/2018/57/57_2018_ma_linguistik_2018_druck.pdf) and is worth 4 LP. A break down of the course credits:

```{r}
#| echo: false
dplyr::tribble(
  ~"LP", ~"type", ~"task",
  "1LP","participation", "working through the lecture materials",
  "1LP","preparation", "readings",
  "1LP", "preparation", "homework due December 20th",
  "1LP", "preparation", "final homework due March 29th"
) |> 
  gt::gt()
```

- Office hours: Wednesdays, 15.00-16.00 (by appointment)

## Course aims

By the end of this course, you will
  
  - blah blah

### What will you learn?

-   linear regression
  + multiple regression
  + logistic regression
  + mixed models
- using the `lme4` package
- how to apply these models appropriately to a variety of data types

### What will you *not* learn?

-   stuff

## Style guide

I bounce between what is typically considered 'American' and 'British' spelling. This will be most notable in my use of -ise and -ize, but will never result in a dropped 'u' from words like *colour*, which is used often plot aesthetics.
